version: '3'
services: 
    influxdb:
      image: influxdb:latest
      container_name: influxdb
      ports:
        - "8086:8086"
      volumes:
        - ./data/influxdb:/var/lib/influxdb
      networks:
        - back-tier

    kapacitor:
      image: kapacitor:latest
      container_name: kapacitor
      command: bash -c "/etc/kapacitor/trader & /entrypoint.sh kapacitord"
      ports:
        - "9092:9092"
      environment:
        KAPACITOR_HOSTNAME: kapacitor
        KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
      volumes:
        - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
        - ./trader:/etc/kapacitor/trader:ro
      networks:
        - back-tier
             
  # Define a Telegraf service
    telegraf:
      image: telegraf:latest
      container_name: telegraf
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      networks:
        - back-tier
      ports:
        - "8092:8092/udp"
        - "8094:8094"
        - "8125:8125/udp"

    grafana:
      image: grafana/grafana:5.0.4
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
          - ./data/grafana:/var/lib/grafana
      networks:
        - back-tier

networks:
    back-tier:

