version: '3'
services: 
    influxdb:
      image: influxdb:latest
      container_name: influxdb
      ports:
        - "8083:8083"
        - "8086:8086"
        - "8090:8090"
      networks:
        - back-tier

    telegraf:
      image: telegraf:latest
      container_name: telegraf

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      networks:
        - back-tier
    frontend:
      image: nginx
      container_name: frontend
      ports:
        - "8080:80"
      volumes:
        - ./frontend:/usr/share/nginx/html


networks:
  back-tier:
